### ISSUE TITLE
Extra Recipes

### ISSUE THREAD

**Issue by m-bowley** [raspberrypilearning/install-raspberry-pi-desktop#7]
Some little extra recipes for more info at points for those who are interested would be great. Like when you talk about the boot menu, could have a drop down to talk about how a computer starts up and finds boot files, on the install screen there could be a little info on what each of the options does. Just a little something extra for the users who want to learn or feel the need to understand everything when they are doing a project.

**Comment by martinohanlon** [comment]
Given this is a guide (rather than a project with a set of learning objectives) I think we should keep this as simple as possible (particularly as its already pretty complicated) and keep the amount of extra information low as to not distract from the instruction.

Great idea @m-bowley , thanks for bringing it up.
